name: Build and Test

on:
  push:
    branches: [ feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Configurer JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache des dépendances Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      - name: Compiler et tester le projet
        run: mvn clean install

      - name: Exécuter les tests unitaires
        run: mvn test
